language: python
python:
  - "3.6"
before_script:
  - pip install python-coveralls
  - cd $TRAVIS_BUILD_DIR/src
script:
  - pip install .
  - cd $TRAVIS_BUILD_DIR/tests
  # Entry points
  - bee-launcher -h
  - bee-monitor -h
  - bee-orchestrator -h
  # Launcher
  - bee-launcher --test-only -l launch_testonly_local.beefile
  - bee-launcher --test-only -l launch_testonly_local.beefile basic_inputs.yml
  - bee-launcher --test-only -l launch_testonly_slurm.beefile
  - bee-launcher --test-only -l launch_testonly_slurm.beefile basic_inputs.yml
after_success:
  - coveralls