language: python
python:
  - "3.6"
before_script:
  - pip install python-coveralls
  - pip install coverage
  - cd $TRAVIS_BUILD_DIR/src
script:
  - pip install .
  - cd $TRAVIS_BUILD_DIR/tests
  # Entry points (path)
  - bee-launcher -h
  - bee-monitor -h
  - bee-orchestrator -h
  # Launcher
  - coverage run -m bee_launcher.__main__.py -h
  - coverage run -m bee_launcher.__main__.py --test-only -l launch_testonly_local.beefile basic_inputs.yml
  - coverage run -m bee_launcher.__main__.py --test-only -l launch_testonly_slurm.beefile basic_inputs.yml
after_success:
  - coveralls